// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonGo.Context;

namespace PokemonGo.Context.Migrations
{
    [DbContext(typeof(PokemonGoContext))]
    partial class PokemonGoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokeBag.Context.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCidade")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("PokeBag.Context.Models.PokeDex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuddyCandyKm")
                        .HasColumnType("int");

                    b.Property<int>("CPMax")
                        .HasColumnType("int");

                    b.Property<int>("CandyForEvolution")
                        .HasColumnType("int");

                    b.Property<int>("EggKm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type1")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Type2")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("PokeDex");
                });

            modelBuilder.Entity("PokeBag.Context.Models.PokemonBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("ChargeAttack")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("CidadeId")
                        .HasColumnType("int");

                    b.Property<int>("CombatPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCaptura")
                        .HasColumnType("datetime2");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<bool>("DisponivelTroca")
                        .HasColumnType("bit");

                    b.Property<string>("Evento")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FastAttack")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int");

                    b.Property<int>("IdPokemonType")
                        .HasColumnType("int");

                    b.Property<double>("IndividualValue")
                        .HasColumnType("float");

                    b.Property<int?>("PokeDexId")
                        .HasColumnType("int");

                    b.Property<bool>("Shiny")
                        .HasColumnType("bit");

                    b.Property<string>("Sombroso")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdPokemonType");

                    b.HasIndex("PokeDexId");

                    b.ToTable("PokemonBag");
                });

            modelBuilder.Entity("PokeBag.Context.Models.PokemonBag", b =>
                {
                    b.HasOne("PokeBag.Context.Models.Cidade", null)
                        .WithMany("Bag")
                        .HasForeignKey("CidadeId");

                    b.HasOne("PokeBag.Context.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBag.Context.Models.PokeDex", null)
                        .WithMany("Bag")
                        .HasForeignKey("IdPokemonType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBag.Context.Models.PokeDex", "PokeDex")
                        .WithMany()
                        .HasForeignKey("PokeDexId");
                });
#pragma warning restore 612, 618
        }
    }
}
